import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import Provider from "./provider";
import Navbar from "@/components/segments/navbar";
import { Container, Stack } from "@chakra-ui/react";
import AuthProvider from "@/providers/auth.provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="vsm-root">
      <body className="chakra-theme dark" style={{ colorScheme: "dark" }}>
        <AuthProvider>
          <Provider>
            <Stack gap={5} minH="100vh">
              <Navbar></Navbar>
              <Container className="prelogin-background" as="main">
                {children}
              </Container>
            </Stack>
          </Provider>
        </AuthProvider>
      </body>
    </html>
  );
}
