import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import Provider from "./provider";
import Navbar from "@/components/segments/navbar";
import { Stack } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
          <Stack gap={5}>
            <Navbar></Navbar>
            {children}
          </Stack>
        </Provider>
      </body>
    </html>
  );
}
